site_name: Concord Documentation
site_description: Documentation of Concord, the Laravel Extension for layered applications
site_author: Attila Fulop

repo_url: https://github.com/artkonekt/concord
repo_name: Concord

docs_dir: docs

theme: readthedocs

extra_css: [extra/rtd.css]

pages:
    - Home: index.md
    - Overview: overview.md
    - Layers: ~
        - Modules: modules.md
        - Boxes: boxes.md
        - Application: application.md
    - Parts: parts.md
        - Configuration: parts-configuration.md
        - Migrations: parts-migrations.md
        - Event-Listener Binding: parts-event-listener-bindings.md
    - Rules: rules.md
    - Map: map.md


google_analytics: ['UA-41126137-7', 'concord.readthedocs.io']